preferences:
  autowire-on-sync-mode: UPDATE_OPTIONAL_DEPENDENCIES
  repositories-mode: FAIL_ON_PROJECT_REPOS

repositories:
  aliyun-google-mirror:
  aliyun-maven-central-mirror:
  aliyun-maven-public-mirror:
  aliyun-jcenter-mirror:
  gradle-plugin-portal:
    scope: PLUGINS
  jit-pack:
  google:
  maven-central:
  sonatype-oss-releases:
  rovo89-xposed-api:
    scope: LIBRARIES
    url: https://api.xposed.info/
    content:
      include:
        group: de.robv.android.xposed

plugins:
  com.android.library:
    alias: android-library
    version: 8.11.0
  com.android.application:
    alias: android-application
    version: 8.11.0
  org.jetbrains.kotlin.android:
    alias: kotlin-android
    version: 2.2.0
  com.google.devtools.ksp:
    alias: kotlin-ksp
    version: 2.2.0-2.0.2
  org.jetbrains.kotlin.plugin.compose:
    alias: android-compose
    version: 2.2.0
  com.google.dagger.hilt.android:
    alias: dagger.hilt
    version: 2.56.2

libraries:
  de.robv.android.xposed:
    api:
      version: 82
      repositories: rovo89-xposed-api
  com.highcapable.yukihookapi:
    api:
      version: 1.3.0
    ksp-xposed:
      version-ref: <this>::api
  com.highcapable.kavaref:
    kavaref-core:
      version: 1.0.1
    kavaref-extension:
      version: 1.0.1
  com.github.duanhong169:
    drawabletoolbox:
      version: 1.0.7
  androidx.core:
    core-ktx:
      version: 1.16.0
  androidx.appcompat:
    appcompat:
      version: 1.7.1
  com.google.android.material:
    material:
      version: 1.12.0
  androidx.constraintlayout:
    constraintlayout:
      version: 2.2.1
  androidx.test.ext:
    junit:
      version: 1.3.0
  androidx.test.espresso:
    espresso-core:
      version: 3.7.0
  junit:
    junit:
      version: 4.13.2
  androidx.annotation:
    annotation:
      version: 1.9.1
  org.jetbrains.kotlinx:
    kotlinx-serialization-json:
      version: 1.8.1
    kotlinx-coroutines-core:
      version: 1.9.0
  com.squareup.okhttp3:
    okhttp:
      version: 4.12.0
  com.google.code.gson:
    gson:
      version: 2.11.0
  androidx.compose.ui:
    ui-tooling-preview-android:
      version: 1.8.3
    ui-tooling:
      version: 1.4.0
  com.github.niki914.Zephyr:
    tools:
      version: 3.1.0
    provider:
      version: 3.1.0
    log:
      version: 3.1.0
  com.google.dagger:
    hilt-android:
      version: 2.56.2
    hilt-android-compiler:
      version: 2.56.2